---

name:
    hledger-graphs
version:
    0.1.0.0
github:
    prikhi/hledger-graphs
homepage:
    https://github.com/prikhi/hledger-graphs#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020 Pavan Rikhi
category:
    Console, Finance
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Generate Graphs from your HLedger Journal.

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - Chart
        - data-default
        - hledger-lib
        - mtl
        - text

executables:
    hledger-graphs:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - hledger-graphs
            - Chart
            - Chart-diagrams
            - diagrams-lib
            - diagrams-svg
            - hledger-lib

tests:
    hledger-graphs-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - hledger-graphs
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
